TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += devSmarPod.db
DB_INSTALLS += $(TOP)/SmarPodSup/devSmarPod.proto

#=======================================
include $(TOP)/configure/RULES
